### ISSUE TITLE
Consider using unsafe-libyaml crate over libyaml-sys

### ISSUE THREAD

**Issue by dtolnay** [fatemender/libyaml-rs#1]
I recently transpiled libyaml from C to Rust, and I am using it as the YAML backend for the widely used `serde_yaml` crate. Here is the crate: https://github.com/dtolnay/unsafe-libyaml.

The transpiled version is pure-Rust code so it has the following advantages:

- It completely fixes this limitation quoted in your readme:

    > _"the `yaml` library must be available on the system, no attempt is made to build it from source"_

    Since `unsafe-libyaml` is just ordinary pure-Rust code, and published to crates.io, your crate can depend on it directly from crates.io and it'll get built by Cargo / rustc the same as any other Rust library.

- It enables you to use Miri (https://github.com/rust-lang/miri) to validate and debug the unsafe code in this crate, which can't possibly work in the presence of FFI calls since Miri relies on abstract interpretation and uses a memory layout that isn't compatible with C FFI.

- The API is identical to libyaml.

Even if you decide to keep libyaml-sys for the purpose of the published crate, the second bullet mean it might make sense to create some kind of mode (private or unpublished) that will swap `unsafe-libyaml` in place of `libyaml-sys` so that you're able to run Miri in CI or for debugging.

**Comment by fatemender** [comment]
Hi!  Sorry for the late reply, been away.

Thanks for the suggestion, seems like a completely reasonable thing to do.  Will update to use `unsafe-libyaml` in a few days.

**Comment by fatemender** [comment]
I've run into the following problem with `unsafe-libyaml`.  In order to emit a document start event, I need the `yaml_version_directive_t` and `yaml_tag_directive_t` structures filled out.  However, these are marked `#[non_exhaustive]` in `unsafe-libyaml` making initialization impossible.  I see that `serde_yaml` uses defaults (null pointers) there which is perfectly reasonable for a serde backend but currently this crate (`libyaml`) allows non-default values and switching to `unsafe-libyaml` would force me to remove that.

Is there any particular reason for the `#[non_exhaustive]` annotation?

**Comment by fatemender** [comment]
Follow-up: I get the idea that additional fields might be added in the future and zero-initializing the entire structure and then overwriting the known fields would probably work, but is there any guarantee in the original (C) `libyaml` about field layout preservation in structures?  I don't see one.

**Comment by dtolnay** [comment]
I don't understand what you mean by field layout preservation, but libyaml's API for structs (in both C and Rust) is that you uninitialize (if you are passing to a <kbd>▢_initialize</kbd> function) or zero-initialize (if you are passing to any other function) and then set the fields you care about. New fields can be added to any structure at any time, in both C and unsafe-libyaml.

Uninitialize in C:

```c
yaml_parser_t parser;
yaml_parser_initialize(&parser);
```

Uninitialize in Rust:

```rust
let mut parser = MaybeUninit::<yaml_parser_t>::uninit();
let parser = parser.as_mut_ptr();
yaml_parser_initialize(parser);
```

Zero initialize in C:

```c
yaml_version_directive_t version_directive = {.major=1, .minor=2};
```

Zero initialize in Rust:

```rust
let mut version_directive = MaybeUninit::<yaml_version_directive_t>::zeroed();
let version_directive = version_directive.as_mut_ptr();
(*version_directive).major = 1;
(*version_directive).minor = 2;
```

**Comment by fatemender** [comment]
Thanks for the clarification, I failed to find this guarantee about zero initialization being sufficient in the docs.  Also the test code (e.g. https://github.com/yaml/libyaml/blob/master/tests/run-emitter-test-suite.c#L64-L68) suggests that there may be no other fields since this uses `malloc`, not `calloc`.

**Comment by dtolnay** [comment]
The `malloc` does not tell you that there will not be new fields. For example libyaml could do:

```diff
- if (!yaml_emitter_write_indicator(emitter, "%YAML", 1, 0, 0))
+ if (!yaml_emitter_write_indicator(emitter, "%YAML 1.", 1, 0, 0))
      return 0;
- if (event->data.document_start.version_directive->minor == 1) {
-     if (!yaml_emitter_write_indicator(emitter, "1.1", 1, 0, 0))
-         return 0;
- }
- else {
-     if (!yaml_emitter_write_indicator(emitter, "1.2", 1, 0, 0))
+ char minor[11];
+ sprintf(minor, "%d", event->data.document_start.version_directive->minor);
+ if (!yaml_emitter_write_indicator(emitter, minor, 0, 0, 0))
+     return 0;
+ if (event->data.document_start.version_directive->minor >= 18 &&
+         event->data.document_start.version_directive->indicator)
+ {
+     if (!yaml_emitter_write_indicator(emitter, "~>", 0, 0, 0))
+         return 0;
+     if (!yaml_emitter_write_indicator(emitter,
+                 event->data.document_start.version_directive->indicator, 0, 0, 0))
          return 0;
  }
```

where some new field applies only for the appropriate range of values of the older fields.

**Comment by fatemender** [comment]
Fair point.  Thank you again.
